
package asociaciones.pantallas;

import asociaciones.entidades.Curso;
import asociaciones.entidades.Estudiante;
import asociaciones.entidades.Profesor;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author tokiro
 */
public class PantallaEstu extends javax.swing.JFrame {

    private Curso curso;
    
    /**
     * Creates new form PantallaEstudiantes
     */
    public PantallaEstu(Curso curso) {
        initComponents();
        this.curso = curso;
        
    }

    public List<Estudiante> buscar(String criterio) {
        return new ArrayList<>();
    }

    public void eliminar(Estudiante estudiante) {
        //TODO:implementar
    }

    public void agregar(Estudiante estudiante) {
        Estudiante[] estudiantes = curso.getEstudiantes();
        int tamaño = estudiantes.length;
        for (int i = 0; i < tamaño; i++) {
            if (estudiantes[i] != null
                    && !estudiantes[i].getNombre().isEmpty()) {
                estudiantes[i] = estudiante;
                return;
            }

            if (estudiantes[i] == null) {
                estudiantes[i] = estudiante;
                return;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregaEstu = new javax.swing.JButton();
        btnEliminaEstu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEstu = new javax.swing.JList<String>();
        btnSalirEstu = new javax.swing.JButton();
        txtBuscaEstu = new javax.swing.JTextField();
        btnBuscaEstu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAgregaEstu.setText("Agregar");
        btnAgregaEstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregaEstuActionPerformed(evt);
            }
        });

        btnEliminaEstu.setText("Eliminar");
        btnEliminaEstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaEstuActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListEstu);

        btnSalirEstu.setText("Salir");
        btnSalirEstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirEstuActionPerformed(evt);
            }
        });

        btnBuscaEstu.setText("Buscar");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Estudiantes de: [ ]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBuscaEstu, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscaEstu)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalirEstu)
                                .addGap(81, 81, 81)
                                .addComponent(btnAgregaEstu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminaEstu))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(53, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscaEstu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaEstu))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregaEstu)
                    .addComponent(btnEliminaEstu)
                    .addComponent(btnSalirEstu))
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregaEstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregaEstuActionPerformed

        Estudiante estudiante = new Estudiante();
        PantallaEditarEstu editarEstu = new PantallaEditarEstu(estudiante);
        editarEstu.setVisible(true);
    }//GEN-LAST:event_btnAgregaEstuActionPerformed

    private void btnEliminaEstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaEstuActionPerformed
        int eli = jListEstu.getSelectedIndex();
        
    }//GEN-LAST:event_btnEliminaEstuActionPerformed

    private void btnSalirEstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirEstuActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirEstuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaEstu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaEstu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaEstu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaEstu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Curso curso = new Curso("", 0, "");
                new PantallaEstu(curso).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregaEstu;
    private javax.swing.JButton btnBuscaEstu;
    private javax.swing.JButton btnEliminaEstu;
    private javax.swing.JButton btnSalirEstu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListEstu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscaEstu;
    // End of variables declaration//GEN-END:variables
}
